name: Deploy to EC2

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deployment repository
        uses: actions/checkout@v4

      - name: Copy deployment files to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            docker-compose.prod.yml
            prometheus.yml
            tempo.yaml
            loki-config.yaml
            otel-collector-config.yaml
            grafana
          target: /home/ubuntu/todo

      - name: Deploy application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            cd /home/ubuntu/todo

            echo "==============================="
            echo "Deployment Files"
            echo "==============================="
            ls -R

            echo "==============================="
            echo "Pulling latest Docker images..."
            echo "==============================="
            docker compose -f docker-compose.prod.yml pull

            echo "==============================="
            echo "Stopping old containers..."
            echo "==============================="
            docker compose -f docker-compose.prod.yml down

            echo "==============================="
            echo "Starting new containers..."
            echo "==============================="
            docker compose -f docker-compose.prod.yml up -d

            echo "==============================="
            echo "Removing unused Docker images..."
            echo "==============================="
            docker image prune -f

            echo "==============================="
            echo "Running Containers"
            echo "==============================="
            docker compose -f docker-compose.prod.yml ps

            echo "==============================="
            echo "Deployment Successful!"
            echo "==============================="